name: "Jeremy Tuloup [JTP]- Blog"
description: "Experiments, algorithms, data and game jams"
url: http://www.jtp.io
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title.html
paginate: 50