name: "Jeremy Tuloup's Blog"
description: "Experiments, algorithms, data and game jams"
url: https://www.jtp.io
enforce_ssl: www.jtp.io
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
highlighter: pygments
permalink: /:year/:month/:day/:title.html
paginate: 50