name: "Jeremy Tuloup"
description: "math, puzzles, data science, visualization and game jams"
url: https://www.jtp.io
enforce_ssl: www.jtp.io
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
  highlighter: rouge
permalink: /:year/:month/:day/:title.html
