// @ts-check
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import astro from "eslint-plugin-astro";
import solid from "eslint-plugin-solid";
import globals from "globals";

const TS_FILES = ["**/*.ts", "**/*.tsx"];

export default [
  // `src/env.d.ts` is generated by Astro; `dist`/`.astro` are build output.
  { ignores: ["dist/", ".astro/", "src/env.d.ts"] },

  js.configs.recommended,

  // Scope TypeScript to TS files so its rules don't leak onto the plain
  // browser scripts in `public/` or the Node config files.
  ...tseslint.configs.recommended.map((config) => {
    const files = /** @type {{ files?: string[] }} */ (config).files;
    return { ...config, files: files ?? TS_FILES };
  }),

  // Solid components are hydrated in the browser.
  {
    files: ["**/*.tsx"],
    ...solid.configs["flat/typescript"],
  },
  {
    files: TS_FILES,
    languageOptions: { globals: globals.browser },
  },

  // Astro files — the plugin wires up its own parser and globals.
  ...astro.configs["flat/recommended"],

  // Static browser scripts served as-is from `public/`.
  {
    files: ["public/**/*.js"],
    languageOptions: { globals: globals.browser },
  },

  // Node config files.
  {
    files: ["*.config.{js,mjs}", "eslint.config.js"],
    languageOptions: { globals: globals.node },
  },
];
